name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy to EC2
        env:
          EC2_USER: ec2-user
          EC2_HOST: ${{ secrets.EC2_HOST }}
          KEY_FILE: ${{ secrets.KEY_FILE }}
        run: |
          echo "${{ secrets.KEY_FILE }}" > key.pem
          chmod 400 key.pem
          scp -i key.pem -o StrictHostKeyChecking=no -r ./* $EC2_USER@$EC2_HOST:/home/ec2-user/hello-world
          ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ec2-user/hello-world
            npm install
            npm run build
            pm2 stop nextjs-hello || true
            pm2 start npm --name "nextjs-hello" -- run start
            pm2 save
          EOF
